
OK = "OK"
ERR_BAD_PARAMS = "ERR_BAD_PARAMS"
ERR_SERVER_EXCEPTION = "ERR_SERVER_EXCEPTION"
ERR_REQ_DL_FAILED = "ERR_REQ_DL_FAILED"
ERR_BEGIN_DL_FAILED = "ERR_BEGIN_DL_FAILED"
ERR_DFS_PUT_FAILED = "ERR_DFS_PUT_FAILED"
ERR_NOT_FOUND = "ERR_NOT_FOUND"

UFA_OK = "Ok"
W_OK = "ok"
W_ERR_SERVER_EXCEPTION = "ServerError"
W_ERR_BAD_PARAMS = "BadParams"
W_ERR_HASH = "HashErr"
W_ERR_REQUL_FAILED = "ReqUlFailed"
W_ERR_REQUL_EXC = "ReqUlExc"
W_ERR_ULBLK_FAILED = "UlBlkFailed"
W_ERR_ULBLK_EXC = "UlBlkExc"
W_ERR_COMMIT_FAILED = "CmtFailed"
W_ERR_COMMIT_EXC = "CmtExc"
W_ERR_ULBLKMETA_FAILED = "UlBlkMetaFailed"
W_ERR_ULBLKMETA_EXC = "UlBlkMetaExc"

HTTP_OK = 200
HTTP_PART = 206
HTTP_302 = 302
HTTP_BAD_PARAMS = 400
HTTP_FORBIDDEN = 403
HTTP_NOT_FOUND = 404
HTTP_INTERNAL_ERROR = 500